# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('horse_in_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.HorseInRun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='horseinrun',
            name='user',
            field=models.ManyToManyField(through='mainapp.Bet', to=settings.AUTH_USER_MODEL),
        ),
    ]
