# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20171227_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jockey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
        migrations.AlterField(
            model_name='bet',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='horse_in_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.HorseInRun', verbose_name='Ставка на лошадь'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.RemoveField(
            model_name='horse',
            name='jockey',
        ),
        migrations.AlterField(
            model_name='horseinrun',
            name='horse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Horse', verbose_name='Лошадь'),
        ),
        migrations.AlterField(
            model_name='horseinrun',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Run', verbose_name='Забег'),
        ),
        migrations.AlterField(
            model_name='run',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='run',
            name='place',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.TimeField(verbose_name='Время'),
        ),
        migrations.AddField(
            model_name='horse',
            name='jockey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Jockey', verbose_name='Жокей'),
        ),
    ]
