# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-06 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20171227_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='place_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='меcто'),
        ),
    ]
