# Generated by Django 2.2.6 on 2019-12-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
