# Generated by Django 2.2.6 on 2019-12-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorisation', '0003_myuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cash',
            field=models.CharField(max_length=100),
        ),
    ]
